rest_api:
    resource: "@RestApiBundle/Controller/"
    type:     rest
    prefix:   /api

back:
    resource: "@BackBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#    prefix:   /user-profile/

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
 #api   
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api-documentation.html